feat: api core message changed

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -195,12 +195,16 @@ jobs:
     # Only dispatch deploy if:
     # - Any project build is affected by the latest changes.
     # - The branch is main or release.
-    if: |
-      always() &&
-      (needs.tag.result == 'success' || needs.tag.result == 'skipped') &&
-      (${{ fromJson(needs.get-affected.outputs.build)[0] }}) &&
-      (github.event.pull_request.base.ref == '') &&
-      (needs.branch-info.outputs.current-branch == 'main' || needs.branch-info.outputs.current-branch == 'release')
+    env:
+      IS_TAG_STEP_COMPLETED: (needs.tag.result == 'success' || needs.tag.result == 'skipped')
+      IS_BUILD_REQUIRED: ${{ fromJson(needs.get-affected.outputs.build)[0] }}
+      IS_MAIN_OR_RELEASE_BRANCH: (needs.branch-info.outputs.current-branch == 'main') || (needs.branch-info.outputs.current-branch == 'release')
     steps:
+      - name: Print requirements
+        run: |
+          echo "IS_TAG_STEP_COMPLETED=$IS_TAG_STEP_COMPLETED"
+          echo "IS_BUILD_REQUIRED=$IS_BUILD_REQUIRED"
+          echo "IS_MAIN_OR_RELEASE_BRANCH=$IS_MAIN_OR_RELEASE_BRANCH"
       - name: Dispatch workflow event
+        if: always() && $IS_TAG_STEP_COMPLETED == true && $IS_BUILD_REQUIRED == true && $IS_MAIN_OR_RELEASE_BRANCH == true
         run: echo "Dispatching deploy event..."
